### ISSUE TITLE
Remove console.log / console.warn

### ISSUE THREAD

**Issue by donlucacorleone** [Syed-Umair/check-network-status#15]
Although `console.log` and `console.warn` messages are very useful, I think you should remove them when in production.
Or you could use an option to programmatically toggle them.

Just my 2 cents.

**Comment by Syed-Umair** [comment]
Hi @donlucacorleone , Thanks for raising the issue. It makes sense to remove it. I will patch this.

**Comment by Syed-Umair** [comment]
Fixed in https://github.com/Syed-Umair/check-network-status/releases/tag/v1.2.3

@donlucacorleone confirm by updating the module and let me know if you face any other issues. Thanks for using this module.
